version: '3.8'

services:
    nextjs-nginx-ssl:
        image: pcaaaal/pascal-burri-com:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:80'
            - '443:443'
